name: introducao_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  intl: ^0.20.2
  my_simple_package:
    path: ./packages/my_simple_package

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
